# Inspired by http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls/

language: emacs-lisp
sudo: false

env:
  matrix:
    - EVM_EMACS=emacs-24.3
    - EVM_EMACS=emacs-24.4
    - EVM_EMACS=emacs-24.5
    - EVM_EMACS=emacs-25.1

before_install:
  - export PATH="$HOME/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install ${EVM_EMACS}-travis --use --skip

script:
  - emacs --version
  - make elc
  - make check-ert
  - make indent-test

notifications:
  email: true
